# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "428872aea789738230c8343e6cf2ef0e"
name = "price-feed"
application_url = "https://example.com"
embedded = false

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
